### PR TITLE
Event functionality for enums

### PR DESCRIPTION
**Pull request by Davidnadejdin**

### CODE REVIEW

**Comment by fulopattila122** [comment]
What is the purpose of this PR?

**Comment by Davidnadejdin** [comment]
> What is the purpose of this PR?

https://github.com/artkonekt/enum-eloquent/issues/9 issue

**Comment by fulopattila122** [comment]
Removing the base package and moving it here is a definite no-go.

**Comment by Davidnadejdin** [comment]
> Removing the base package and moving it here is a definite no-go.

but you can’t inherit from the base class

**Comment by fulopattila122** [comment]
> but you can’t inherit from the base class

Why?

**Comment by Davidnadejdin** [comment]
> > but you can’t inherit from the base class
> 
> Why?

private methods needed

**Pull request closed without merging**
